### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ssfrr** [Keno/TexExtensions.jl#9]
Hopefully things have stabilized enough with 0.5 that the current fixes in master will be good to keep it compatible. It would be great to tag this release before 0.5 comes out of RC.

**Comment by lostanlen** [comment]
This affects the [LibSndFile.jl](https://github.com/JuliaAudio/LibSndFile.jl) package in many places. It would be good to integrate PR #7 to the latest stable branch. cc @Keno

**Comment by garrison** [comment]
Bump

**Comment by Keno** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10263

**Comment by garrison** [comment]
Thanks!
